import { fixupPluginRules } from "@eslint/compat";
import eslintJs from "@eslint/js";
import prettierEslintConfig from "eslint-config-prettier/flat";
import importEslintPlugin from "eslint-plugin-import";
import perfectionist from "eslint-plugin-perfectionist";
import unusedImportEslintPlugin from "eslint-plugin-unused-imports";

import type { Config, ConfigArray } from "./types.d.ts";

export const commonESLintConfig = [
  importEslintPlugin.flatConfigs.recommended,
  eslintJs.configs.recommended as Config,
  prettierEslintConfig,
  perfectionist.configs["recommended-natural"],
  {
    name: "@2025-boilerplate/eslint-config/common",

    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
    },
    linterOptions: {
      reportUnusedDisableDirectives: true,
    },
    plugins: {
      "unused-imports": fixupPluginRules(unusedImportEslintPlugin),
    },
    rules: {
      "array-callback-return": [
        "error",
        { allowImplicit: true, checkForEach: true },
      ],
      "block-scoped-var": "error",
      camelcase: ["error"],
      "class-methods-use-this": "error",
      curly: ["error", "all"],
      "default-case": "error",
      "default-case-last": "error",
      "default-param-last": "error",
      "dot-notation": "error",
      eqeqeq: "error",
      "func-name-matching": [
        "error",
        {
          considerPropertyDescriptor: true,
        },
      ],
      "func-style": ["error", "expression"],
      "grouped-accessor-pairs": ["error", "getBeforeSet"],
      "guard-for-in": ["error"],
      "import/default": "error",
      "import/export": "error",
      "import/named": "error",
      "import/namespace": "error",
      "import/newline-after-import": "warn",
      "import/no-absolute-path": "error",
      "import/no-anonymous-default-export": "error",
      "import/no-cycle": "error",
      "import/no-deprecated": "error",
      "import/no-duplicates": "error",
      "import/no-dynamic-require": "error",
      "import/no-extraneous-dependencies": [
        "error",
        {
          devDependencies: false,
          optionalDependencies: false,
        },
      ],
      "import/no-mutable-exports": "error",
      "import/no-named-default": "error",
      "import/no-namespace": ["error", { ignore: ["*.css"] }],
      "import/no-relative-packages": "error",
      "import/no-self-import": "error",
      "import/no-unresolved": ["error", { caseSensitiveStrict: true }],
      "import/no-unused-modules": "error",
      "import/no-useless-path-segments": "error",
      "import/no-webpack-loader-syntax": "error",
      "line-comment-position": ["error", { position: "above" }],
      "lines-between-class-members": "error",
      "logical-assignment-operators": [
        "error",
        "always",
        { enforceForIfStatements: true },
      ],
      "max-classes-per-file": [
        "error",
        {
          ignoreExpressions: true,
          max: 1,
        },
      ],
      "no-alert": "error",
      "no-array-constructor": "error",
      "no-await-in-loop": "error",
      "no-caller": "error",
      "no-console": ["error", { allow: ["error"] }],
      "no-constant-binary-expression": "error",
      "no-constructor-return": "error",
      "no-continue": "error",
      "no-else-return": ["warn", { allowElseIf: false }],
      "no-empty-function": "error",
      "no-eval": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-extra-label": "error",
      "no-floating-decimal": "error",
      "no-implicit-coercion": ["error", { boolean: false }],
      "no-implicit-globals": "error",
      "no-implied-eval": "error",
      "no-inline-comments": "error",
      "no-invalid-this": "error",
      "no-iterator": "error",
      "no-label-var": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-lonely-if": "error",
      "no-loop-func": "error",
      "no-multi-assign": "error",
      "no-negated-condition": "error",
      "no-nested-ternary": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-object": "error",
      "no-new-wrappers": "error",
      "no-octal-escape": "error",
      "no-param-reassign": "error",
      "no-plusplus": "error",
      "no-promise-executor-return": "error",
      "no-proto": "error",
      "no-return-assign": "error",
      "no-return-await": "error",
      "no-script-url": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-shadow": "error",
      "no-template-curly-in-string": "error",
      "no-throw-literal": "error",
      "no-undef-init": "error",
      "no-underscore-dangle": ["error", { allow: ["__webpack_public_path__"] }],
      "no-unmodified-loop-condition": "error",
      "no-unneeded-ternary": "error",
      "no-unreachable": "error",
      "no-unreachable-loop": "error",
      "no-unused-expressions": "error",
      "no-unused-private-class-members": "error",
      // Disabled in favor of "unused-imports/no-unused-vars"
      "no-unused-vars": "off",
      "no-use-before-define": ["error", { variables: false }],
      "no-useless-call": "error",
      "no-useless-computed-key": "error",
      "no-useless-concat": "error",
      "no-useless-constructor": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "no-var": "error",
      "no-void": "error",
      "object-shorthand": ["error", "properties"],
      "operator-assignment": ["error", "always"],
      "perfectionist/sort-imports": ["warn"],
      "perfectionist/sort-named-imports": ["warn"],
      "perfectionist/sort-object-types": [
        "warn",
        {
          partitionByNewLine: true,
        },
      ],
      "perfectionist/sort-objects": [
        "warn",
        {
          partitionByNewLine: true,
        },
      ],
      "prefer-arrow-callback": [
        "error",
        {
          allowNamedFunctions: true,
        },
      ],
      "prefer-const": [
        "error",
        { destructuring: "all", ignoreReadBeforeAssign: true },
      ],
      "prefer-destructuring": [
        "error",
        {
          array: true,
          object: true,
        },
        {
          enforceForRenamedProperties: false,
        },
      ],
      "prefer-named-capture-group": "off",
      "prefer-numeric-literals": "off",
      "prefer-object-has-own": "error",
      "prefer-object-spread": "error",
      "prefer-promise-reject-errors": "error",
      "prefer-regex-literals": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "error",
      "quote-props": ["error", "as-needed"],
      radix: "error",
      "require-atomic-updates": "error",
      "require-await": "error",
      "sort-vars": "error",
      "spaced-comment": ["error", "always"],
      "symbol-description": "error",
      "unused-imports/no-unused-imports": "warn",
      "unused-imports/no-unused-vars": [
        "warn",
        {
          args: "after-used",
          argsIgnorePattern: "^_",
          ignoreRestSiblings: true,
          vars: "all",
        },
      ],
      "vars-on-top": "error",
      yoda: ["error", "never"],
    },
  },
] as const satisfies ConfigArray;
